name: ElectionSystem
version: 1.0.0
main: com.pecing.electionplugin.ElectionSystem
api-version: "1.21"
description: Election system for Minecraft
author: Pecing

commands:
  vote:
    description: Vote for a candidate
    usage: /vote [candidate]
  election:
    description: Manage the election
    usage: /election <create|remove> <player>
  results:
    description: Show election results
    usage: /results
  resetelection:
    description: Reset the entire election
    usage: /resetelection

permissions:
  electionplugin.admin:
    description: Permission to manage elections
    default: op